### ISSUE TITLE
Symfony5 support

### ISSUE THREAD

**Issue by Adrians-G** [M6Web/DaemonBundle#34]
Hi guys, do you plan to support this library for Symfony5? 

Are there any changes except composer.json needed?

**Comment by Adrians-G** [comment]
Created PR https://github.com/M6Web/DaemonBundle/pull/36

**Comment by Oliboy50** [comment]
closed since [6.0.0](https://github.com/M6Web/DaemonBundle/releases/tag/v6.0.0) has been released
